# Generated by Django 6.0.1 on 2026-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
